version: '3.8'
services:
  marimo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    command: marimo edit notebook.py --host 0.0.0.0 --port 8888
    volumes:
      - .:/app
